#!/bin/node

const readFile = require('read-file')
const { Command } = require('commander');
const evaluate = require('./evaluate');
const program = new Command();

program
    .name('runner.js')
    .description('Evaluates the parse tree generated by Nearley Lambda parser')
    .version('0.1.0');

program.command('eval')
    .description('Evaluate the parse tree')
    .argument('<input>', 'input parse tree file')
    .action((input) => {
        try {
            const source = JSON.parse(readFile.sync(input, 'utf-8'))
            console.log(evaluate(source))
        } catch(e) {
            console.log(e.message)
        }
    });

program.parse();